spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: resourceService
          uri: lb://resource-service
          predicates:
            - Path=/resources/**
        - id: songService
          uri: lb://song-service
          predicates:
            - Path=/songs/**
      filters:
        - name: ErrorHandlingFilter

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-svc:8761/eureka
  instance:
    preferIpAddress: true
    metadataMap:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
      "prometheus.port": 8080

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true